### ISSUE TITLE
Create a simple CHT mesh with extended fluid domain

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#10]
This issue can be closed when the aforementioned CHT mesh has been created, as a rough approximation of molten salt from from the channel into the upper plenum.

**Comment by anshchaube** [comment]
![mesh](https://user-images.githubusercontent.com/31393012/61152682-b76ab800-a4ae-11e9-8f8c-c18e070b3cdd.png)
Domain decomposition similar to this is required in the source extrusion surface for the upper plenum region, to make the mesh for the channel salt and the upper plenum salt conformal.

**Comment by anshchaube** [comment]
`prenek` will not accept my mesh files' boundary conditions. My graphite boundaries are similar to the previous CHT case that we ran, which we know is functional
```
      do iel=1,nelv
          do ifc=1,2*ndim
              id_face = bc(5,ifc,iel,1)
              bc(5,ifc,iel,2) = id_face
              bc(4,ifc,iel,2) = bc(5,ifc,iel,2)
              if (id_face.eq.10) then       ! Inlet
                  cbc(ifc,iel,1) = 'W  '
                  cbc(ifc,iel,2) = 'I  '
              elseif (id_face.eq.20) then   ! Outlet
                  cbc(ifc,iel,1) = 'W  '
                  cbc(ifc,iel,2) = 'I  ' 
              elseif (id_face.eq.30) then   ! Sym plane 1
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
              elseif (id_face.eq.40) then   ! Sym plane 2
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
      	      elseif (id_face.eq.50) then   ! Inner wall
                  cbc(ifc,iel,1) = 'W  '
                  cbc(ifc,iel,2) = 'E  '
      	      elseif (id_face.eq.60) then   ! Outer wall
                  cbc(ifc,iel,1) = 'W  '
                  cbc(ifc,iel,2) = 'I  '
              endif
          enddo
      enddo
```

**Comment by anshchaube** [comment]
For my fluid domain, I have meshed the inner channel as one extruded volume, and the volume from the channel top to the plenum top as the other cuboidal extruded volume. I have double checked side sets IDs, mesh quality/gaps, and have tried including or removing the internal BCs between the two volumes' interface (at the channel top/plenum bottom -- see sideset 1100 below) - however I have had no success.

For the cuboidal mesh of the plenum, the sides (plen1-4 below) have `SYM`, the bottom surfaces that touch the top of the graphite have `W,E`. I do not think I have too many `E`s in my mesh.

```
      do iel=1,nelv
          do ifc=1,2*ndim
              id_face = bc(5,ifc,iel,1)
              bc(5,ifc,iel,2) = id_face
              bc(4,ifc,iel,2) = bc(5,ifc,iel,2)
              if (id_face.eq.100) then       ! Inlet
                  cbc(ifc,iel,1) = 'v  '
                  cbc(ifc,iel,2) = 't  '
              elseif (id_face.eq.200) then   ! Outlet
                  cbc(ifc,iel,1) = 'O  '
                  cbc(ifc,iel,2) = 'O  ' 
              elseif (id_face.eq.300) then   ! plen1
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
              elseif (id_face.eq.400) then   ! plen2
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
     	      elseif (id_face.eq.500) then   ! plen3
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
     	      elseif (id_face.eq.600) then   ! plen4
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
     	      elseif (id_face.eq.700) then   ! inner wall
                  cbc(ifc,iel,1) = 'W  '
                  cbc(ifc,iel,2) = 'E  '
     	      elseif (id_face.eq.800) then   ! upper wall
                  cbc(ifc,iel,1) = 'W  '
                  cbc(ifc,iel,2) = 'E  '
     	      elseif (id_face.eq.900) then   ! sym plane1
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
     	      elseif (id_face.eq.1000) then   ! sym plane2
                  cbc(ifc,iel,1) = 'SYM'
                  cbc(ifc,iel,2) = 'SYM'
     	      elseif (id_face.eq.1100) then   ! sym plane2
                  cbc(ifc,iel,1) = 'E  '
                  cbc(ifc,iel,2) = 'E  '
              endif
          enddo
      enddo
```

**Comment by anshchaube** [comment]
@dshaver-ANL please let me know if you have any thoughts on what might be causing this error. 

Also, where the plenum fluid volume and the channel fluid volume have common surfaces(at the top of the channel), should I :
a - create a sideset of the common internal surfaces, and set `E` for both fields?
b - ignore the common surfaces, create no sidesets?

**Comment by dshaver14** [comment]
If prenek is prompting you for boundary conditions, it means there is either an ‘E  ‘, or a ‘   ‘ on an exposed surface (i.e. non-internal).  If you go through the steps manually, it will try to show you which ones are causing the problem, although prenek isn’t really meant to be used in 3D so it might be difficult to see.

The brute force way around this is to never set anything to 'E  ', set it to 'v  ' or 't  ' respectively.  If prenek STILL complains, then you have a surface that you're not accounting for here.  Note that when you load any two rea files into prenek with the standard method, it will set any shared faces to the 'E  ' boundary condition.  When you use the CHT merge in prenek it will convert and thermal BCs on a shared face to 'E  '.

**Comment by anshchaube** [comment]
@dshaver-ANL changing all `W/E` pairs to `v/t` made prenek accept the mesh file BCs. The only surfaces that had E were -
1. The inner wall of the graphite, and the fluid in contact with it, which works fine in other cases.
2. The top of the graphite, and the fluid in the plenum in contact with it. This is a new addition, and possibly the source of the problem.

I haven't found any obvious errors - the sidesets and surface IDs in gmsh for 2 look correct. They seem to be coincident, and I see no irregularities or gaps when meshing it.

**Comment by anshchaube** [comment]
Part of the upper plenum was not conformal and slightly misaligned. Issue fixed by changing the .geo file.
Prenek is accepting the BCs now.

**Comment by anshchaube** [comment]
Simulation not converging. Will play with mesh parameters to refine it further.

**Comment by anshchaube** [comment]
The mesh for the fluid in the plenum has small, thin elements near the outer edge of the channel region of the mesh, and thicker elements in the plenum region of this mesh near the edge. The mesh in the plenum region needs to be remade such that elements of the same thickness are close to each other.

Thin elements are required for obtaining an accurate value of the gradient - hence thin elements are not necessary where there is a symmetry boundary condition (i.e. the outer edge of the plenum)

**Comment by anshchaube** [comment]
<img width="1156" alt="Screen Shot 2019-07-25 at 11 37 08 AM" src="https://user-images.githubusercontent.com/31393012/61892097-b2573100-aed0-11e9-8bf3-1490826383f2.png">
Fixed mesh.

**Comment by anshchaube** [comment]
It works now! Testing the case further on blue waters. This issue should be closed soon.

**Comment by anshchaube** [comment]
@dshaver-ANL temperature blows up to nan, then inf, them reduces to 1e37. CFL goes from 0.3 to 0.6, so I'll try a small DT so that CFL ~0.4.

**Comment by anshchaube** [comment]
Temperature values were blowing up unless variable DT and target CFL options are used. Not sure why.
Everything looks reasonable. Below is a top view of the channel top (before the plenum begins) @dshaver-ANL 
![visit0000](https://user-images.githubusercontent.com/31393012/62493092-de5a9800-b795-11e9-9a0d-6895fcede1f8.png)
EDIT - negative temperatures - need to be rescaled, result of normalization, values are physical.

**Comment by anshchaube** [comment]
![visit0001](https://user-images.githubusercontent.com/31393012/62493719-6b522100-b797-11e9-98c0-6185297a2099.png)
Here, we can see a side view of the region above the upper plenum. A region with negative velocity develops persistently above the plenum. Seems like the recirculation zone that you mentioned @dshaver-ANL . Will try to create a movie/plots with more detailed time resolution.

**Comment by dshaver14** [comment]
Usually the temperature solver isn't too picky about it's time step size, particularly since the CFL is only based on the fluid velocity.  However, this is a high Prandtl number fluid, so you might be seeing some instabilities develop.  As long as you can maintain a CFL of around 0.4 I wouldn't be too concerned.

Negative temperatures are a result of numerical dispersion errors in the solution.  You'll see that the local extrema follow the GLL points on the mesh.  You can either cut them off with a limiter, refine the mesh, or ignore them.

**Comment by dshaver14** [comment]
The latest result you're showing for the z-velocity looks like it's only marginally resolved.  Can you show a few more figures so I get a better idea what I'm looking at and show this same one with the GLL mesh overlaid?

**Comment by anshchaube** [comment]
The write interval was 10s...
https://drive.google.com/file/d/1284l1lflQw_6mQ8s0ueHGa_7e-cJhnl_/view?usp=sharing

**Comment by dshaver14** [comment]
Can you just post the 12 images somewhere?  This definitely looks like it's under resolved to me.

**Comment by anshchaube** [comment]
Sorry. Yeah, I looked more closely, I can see discontinuities where the element boundaries are. I guess I need to remesh with more elements in the z direction - right now we're at 1 layer in z per inch.

https://drive.google.com/open?id=1y-74fTDSNDKecYhE0BsLKoalTqDdff4f

**Comment by anshchaube** [comment]
Aspect ratio min/max/avg: 3.70E+00 7.33E+01 2.07E+01 compared to the previous average of ~100.
I think the results look well resolved. @dshaver-ANL @katyhuff (this is the upper plenum region)

![visit0001](https://user-images.githubusercontent.com/31393012/65779505-7b3e0f80-e10d-11e9-9e0a-fb42e69002d9.png)
![visit0002](https://user-images.githubusercontent.com/31393012/65779510-7d07d300-e10d-11e9-922f-e678369cfcf9.png)

**Comment by anshchaube** [comment]
@dshaver-ANL but the simulation blows up at t=90s
![visit0003](https://user-images.githubusercontent.com/31393012/65779925-4d0cff80-e10e-11e9-9c1a-b42af455723e.png)
![visit0004](https://user-images.githubusercontent.com/31393012/65779930-4ed6c300-e10e-11e9-85f2-f8b66b3d57be.png)

Output:
```
Step  15061, t= 8.9592115E+01, DT= 3.3521520E-09, C=******* 2.5863E+03 2.3731E+00
             Solving for Hmholtz scalars
      15061  Error Hmholtz TEMP     200   2.6775E+12   1.3869E+22   1.0000E-06
      15061  Scalars done  8.9592E+01  2.8043E-01
             Solving for fluid
      15061  Project PRES           8.4626E+28   8.4625E+28   1.0000E+00   8   8
      15061  PRES gmres       200   4.3621E+18   1.3052E+28   1.0000E-05   1.2114E+00   1.5616E+00    F
      15061  Error Hmholtz VELX     200   7.0324E+20   3.0308E+28   1.0000E-08
      15061  Error Hmholtz VELY     200   4.3102E+14   1.4754E+28   1.0000E-08
      15061  Error Hmholtz VELZ     200   1.3859E+24   4.9844E+27   1.0000E-08
             L1/L2 DIV(V)          -1.7505E+17   5.9176E+21
             L1/L2 QTL              0.0000E+00   0.0000E+00
             L1/L2 DIV(V)-QTL      -1.7505E+17   5.9176E+21
             WARNING: DIV(V)-QTL too large!

```

**Comment by anshchaube** [comment]
I'm using bdf2 with variable DT and a target CFL of 0.3. Since we are seeing strong vortices, perhaps my lx1=6 is too low?

**Comment by dshaver14** [comment]
no.  your "vortex" is strong, but it's not turbulent.  Do these images show everything right up to the outlet?  If so, you've got flow coming in the outlet.  This is probably causing all of your issues.  You need to add a call to 'turb_outflow' in userchk.

**Comment by anshchaube** [comment]
Thanks. I spent the morning looking into it... What ratio should the outflow be scaled by in the call to turb_outflow? 1.5 or 2? I see both in the examples.
Also, what does "scaling outflow" mean and how does it affect the incoming flow at the outlet? Does it relate to the amount of artificial pressure or advection added at the outlet?

**Comment by dshaver14** [comment]
Who the heck knows.  Just go with whatever the mean velocity of your flow is, probably 1?  Eh... make it 1.5 just to be sure.  So what this is going to do is cause the fluid in the last few layers of elements on the outlet to expand, resulting in a strong acceleration outward.  It has the same effect as adding a converging nozzle so that all of the flow has no choice but to exit.

**Comment by anshchaube** [comment]
Thanks. The `userchk` looks like this now:
```
      subroutine userchk()

c      implicit none

      include 'SIZE'
      include 'TOTAL'
      
      lt = lx1*ly1*lz1*lelt
      common /myoutflow/ d(lt),w1(lt)      
      ratio = 1.5
      uin = 0

      call turb_outflow(d,w1,ratio,uin)

      if( time.ge.60) iostep = 1000   

      return
      end
```
I'll post results when they are available.

**Comment by anshchaube** [comment]
@dshaver-ANL what genmap tolerance do you use for cases this big? Is it even important? Thanks.

**Comment by anshchaube** [comment]
Since I changed the userchk routine, this is what happens when I compile:
```
** get_limits   === End of Compilation 12 ===
** i8gl_running_sum   === End of Compilation 43 ===
** close_files   === End of Compilation 44 ===
** neknekgsync   === End of Compilation 45 ===
** setnekcomm   === End of Compilation 46 ===
** get_limits_nodt   === End of Compilation 13 ===
** usrdat0   === End of Compilation 14 ===
** usrsetvert   === End of Compilation 15 ===
1501-511  Compilation failed for file pcht.f.
make: *** [usrfile] Error 1
make: *** Waiting for unfinished jobs....
1501-510  Compilation successful for file comm_mpi.f.
"/home/achaube/Nek5000/core/mxm_std.f", 1500-036 (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
.
<many more lines of the same>
.
.
"/home/achaube/Nek5000/core/mxm_std.f", 1500-036 (I) The NOSTRICT option (default at OPT(3)) has the potential to alter the semantics of a program.  Please refer to documentation on the STRICT/NOSTRICT option for more information.
1501-510  Compilation successful for file mxm_std.f.
```

**Comment by dshaver14** [comment]
genmap tolerance usually doesn't matter.  Only if you have very small elements (need a small tolerance) or a poorly made mesh (need a large tolerance).  I just go with 0.01 as my default.

Did Nicolas' suggesting fix the compiler issue?  If you're still having trouble, you can check

dshaver/case2/trans.usr

in the PANDAVal folder.  There's an example there that I use.

**Comment by anshchaube** [comment]
Thanks. I've been using 0.1 or 0.2 (default suggested by genmap). I'll try 0.01 on a couple of other cases that aren't converging. Kind of out of ideas.

Yes, the following compiles:
```
      subroutine userchk()

c      implicit none

      include 'SIZE'
      include 'TOTAL'

      parameter(lt=lx1*ly1*lz1*lelt)
      common /myoutflow/ d(lt),w1(lt)      
      ratio = 1.5
      uin = 0

      call turb_outflow(d,w1,ratio,uin)

      if( time.ge.20) iostep = 1000   

      return
      end
```

**Comment by dshaver14** [comment]
If genmap were the issue you'd get something like "error in general ev", where it can't figure out the boundary conditions for an element.

**Comment by anshchaube** [comment]
Mesh exists and works. The mesh is being further developed and optimized as discussed in #19 #20.
