### ISSUE TITLE
Script gmsh -> prenek cht mesh generation process

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#11]
This issue can be closed when a bash script has been created and tested that can perform the following functions : 

- [x] Generate .msh (v2 ascii) from .geo file
- [x] Can generate re2 using gmsh2nek
- [x] Can generate rea mesh (newrea.out) from nek post-processing
- [x] Can setup rea mesh with rea tail and head
- [x] Can loop over solid and fluid mesh in one working directory doing all of the above
- [x] Merge solid and fluid using prenek

**Comment by anshchaube** [comment]
@dshaver-ANL I'm trying to run `pretex` on an MCS workstation, as you recommended, but it keeps asking me to setup a display. Is there a build option for `prenek` to disable the `nekton` GUI? Thanks.
EDIT - also surprised by this, because I thought `pretex` was the command line version of `prenek`?

**Comment by anshchaube** [comment]
@dshaver-ANL Installing Xming and setting `DISPLAY` to whatever server ID Xming has on Windows worked! Had to change one minor thing - `export DISPLAY=localhost:0.0` *before* ssh-ing into mcs. Thanks!

**Comment by anshchaube** [comment]
Checking `$DISPLAY` on MCS showed localhost:14.0, so I guess the offset was not 12.0?

**Comment by dshaver14** [comment]
I've noticed I get different values depending on which MCS machine I'm logged into.
