### ISSUE TITLE
Mesh stringer tip + fluid

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#14]
Meshing the pyramid tip and the fluid around it is a non-trivial task, since the meshes need to be conformal.
This issue can be closed when the stringer tip and some fluid above it have been meshed successfully and can be merged using prenek.

**Comment by anshchaube** [comment]
http://onelab.info/pipermail/gmsh/2016/010626.html

**Comment by anshchaube** [comment]
Trying to use gmsh's OpenCASCADE kernel to perform boolean operations, ran into multiple errors (`Could not add plane surface / could not create face`). Useful info:
http://onelab.info/pipermail/gmsh/2018/012284.html

**Comment by anshchaube** [comment]
https://gitlab.onelab.info/gmsh/gmsh/issues/370
need to convert all built in entities to OpenCASCADE entities. >:(

**Comment by dshaver14** [comment]
You need to do what now?  Let me ask you a different question.  If you wanted to just run this case in MOLTRES, how would you go about generating the mesh?

**Comment by anshchaube** [comment]
Gmsh has two kernels - the built-in and the OpenCASCADE. I need to OpenCASCADE to perform Boolean operations so I can separate the solid and the fluid meshes for prenek.

For Moltres, I would mesh the solid and fluid together. No need to separate them.

**Comment by dshaver14** [comment]
can't you mesh them together, but as separate blocks, then write the blocks out to different files?

**Comment by anshchaube** [comment]
I think so, actually that's exactly what I'm trying to do. But that would require Boolean operations too, so that the surrounding fluid doesn't overlap with the graphite.

**Comment by anshchaube** [comment]
The way to do it without Boolean operations would be to manually define the coordinates for the fluid volume with the pyramid - like graphite tip cut out from the volume, which will be tricky and could lead to gaps, conformity issues...

**Comment by anshchaube** [comment]
Stringer tip height from Fig. 5.4 TM 728 - approximately 1 " (impossible to be more precise - measured from a "to-scale" diagram"

**Comment by anshchaube** [comment]
No longer necessary - for now, tip and stringer are being meshed together.
