### ISSUE TITLE
Create job script for Cetus

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#16]
This issue can be closed when a script that successfully submits jobs to Cetus has been created.

Resources:
https://www.mcs.anl.gov/hs/software/systems/softenv/softenv-intro.html
https://press3.mcs.anl.gov//atpesc/files/2015/08/Loy.QuickStart.pdf
https://www.alcf.anl.gov/files/2018-01-18%20Getting%20Started%20Mira.pdf
https://www.alcf.anl.gov/user-guides/bgq-cobalt-job-control
https://www.alcf.anl.gov/user-guides/running-jobs-xc40

**Comment by dshaver14** [comment]
We have scripts for cetus, I'll send it to you.


-------- Original message --------

**Comment by anshchaube** [comment]
Thanks!

**Comment by dshaver14** [comment]
see if you can copy it from my directory on Cetus:

/home/dshaver/scripts/nekd

usage is:
$nekd casename nnodes hours minutes project mode

hours, project, and mode are optional arguments
project requires hours to be specified
mode requires hours and project to both be specified

This should work on both Cetus and Mira.

**Comment by anshchaube** [comment]
I can. Thanks!

**Comment by anshchaube** [comment]
https://github.com/arfc/sneks4me/blob/master/scripts/cetusjob

Script finally works (started working on it before this issue was created). May switch to nekd in the future.
