### ISSUE TITLE
Add filter to simulations

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#17]
The turbOutflow example has :
```
filtering = hpfrt # set to none in case of Smagorinski 
filterWeight = 10
filterCutoffRatio = 0.9 
```

Is this an appropriate filter for our simulations? Are these parameters appropriate?

Resources to consider - Pope; Deville, Fischer, Mund.

**Comment by dshaver14** [comment]
what are the flow conditions and what polynomial order (lx1) are you using?

**Comment by anshchaube** [comment]
Re=1000, everything's normalized like it was during the summer for the flat plenum case, lx1 = 6.

**Comment by dshaver14** [comment]
okay.  For a laminar flow the filter isn't really important (everything should be fully resolved).  Just for stability though, use the explicit filter:

`filtering = explicit`
`filterWeight = 0.02`
`filterCutoffRatio = 0.65`

When you run it, check the logfile after the first time step for the qfilt line.  Make sure it's only touching the last 2 modes.

**Comment by anshchaube** [comment]
I searched for `qfilt`, didn't find it. I did see this however:
```
filt amp  .0000  .0000  .0000  .0000  .0050  .0200
filt trn 1.0000 1.0000 1.0000 1.0000  .9950  .9800
```

**Comment by dshaver14** [comment]
That's the one!


-------- Original message --------

**Comment by anshchaube** [comment]
Ah!
```
filt amp  .0000  .0000  .0000  .0000  .0050  .0200
```
So this shows it's only touching the last two modes?
So that I know when I am writing this up, what "modes" are they? Where can I read more about the theory of the filters used by Nek?

And finally, does this mean the filter is working and this issue can be closed?

**Comment by dshaver14** [comment]
The modes are the polynomial approximation orders.  There will be 'lx1' numbers on that line corresponding to the amplitude of the filter.  The filter acts by interpolating the solution to each order,  then rebuilding it and weighting each mode by (1-amp).  By damping the highest order modes, corresponding to the shortest wavelengths, it effectively removes energy from the flow, mimicking a viscous effect and stabilizing the solution.

For a laminar flow, the solution should be well represented on the lower orders and the filter doesn't do anything.  However, if the flow is transitional, it will add diffusivity and can prevent it from transitioning to turbulence.


-------- Original message --------

**Comment by anshchaube** [comment]
Thanks! So, we have some turbulence in the plenum. Is the filter going to take us away from the physical solution by increasing dissipation and reducing vortices, thereby giving us the "wrong" answer?

**Comment by anshchaube** [comment]
~~Future simulations won't have the filter.~~ See discussion below:

**Comment by katyhuff** [comment]
Why not?

**Comment by anshchaube** [comment]
@dshaver-ANL's comment suggests that it's not particularly useful for our case with Re=1000, and it may lead us away from the correct physical answer by adding an artificial diffusivity that unphysically mitigates the very vortices (and any consequent recirculation zones) in the plenum that we're investigating.

**Comment by dshaver14** [comment]
That's not exactly what I meant.  Yes, the filter does add some artificial diffusivity, but it is quite small, and usually only stabilizes the simulation.  I would suggest keeping it on.

**Comment by anshchaube** [comment]
Okay, future simulations will have the filter.
