### ISSUE TITLE
Create salt-channel model in Nek

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#2]
This issue can be closed when a Nek model for the MSRE salt channel, with re2, usr, par and SIZE files, has been created and tested.

**Comment by anshchaube** [comment]
Error from makenek:
```
obj/half-channel.o:` In function `uservp_':
half-channel.f:(.text+0x3): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
half-channel.f:(.text+0xe): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
obj/half-channel.o: In function `userf_':
half-channel.f:(.text+0x23): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
half-channel.f:(.text+0x2e): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
half-channel.f:(.text+0x39): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
obj/half-channel.o: In function `userq_':
half-channel.f:(.text+0x53): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
obj/half-channel.o: In function `userbc_':
half-channel.f:(.text+0x6a): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
half-channel.f:(.text+0x75): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
half-channel.f:(.text+0x80): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
half-channel.f:(.text+0x8b): relocation truncated to fit: R_X86_64_PC32 against symbol `nekuse_' defined in COMMON section in obj/half-channel.o
obj/half-channel.o: In function `useric_':
half-channel.f:(.text+0x9a): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
makefile:119: recipe for target 'nek5000' failed
make: *** [nek5000] Error 1
```

**Comment by anshchaube** [comment]
https://groups.google.com/forum/#!searchin/nek5000/collect2$3A$20error$3A$20ld$20returned$201$20exit$20status/nek5000/2FGjY1fYFW4/CwhTTkPyEwAJ

Possibly reduce mesh size.

Full mesh size - 55512 - same error as above.
Half channel mesh size - ~34k - same error as above

Try coarse mesh.

**Comment by dshaver14** [comment]
A couple more things you could try to really get the problem size down is taking advantage of symmetry planes in the mesh.  This could cut the problem size to 1/4.  If it's still too big to run on your laptop, we could settle for just fully developed flow which would only require a domain that's a couple of diameters long.

**Comment by anshchaube** [comment]
Made coarse mesh with 4k elements.
Made quarter-channel (using SYM BC) with 6k elements. Both compile successfully.
No. of elements that can be compiled - 6k - 12k (upper limit inaccurate).

Both solutions diverge. Inspecting .par and SIZE files.

Misc info:
5k elements + lx1 = 7,8  -> overflows
5k elements + lx1 = 6 -> compiles, diverges
34k elements + lx1 =3, lxd =4 ->compiles

**Comment by anshchaube** [comment]
According to Kirk, the mesh right now is too fine, and I have to compensate for that by lowering lx1(to get it to compile without overflow). This is why the simulation isn't converging. Kirk has asked me to refine the mesh by making a coarse block in the middle and a finer block near the boundary.

**Comment by dshaver14** [comment]
Kirk's judgement is probably correct, but I would expect lx1=6 to be okay.  Can you post a cross section of the mesh?

**Comment by anshchaube** [comment]
Actually, the quarter core mesh has 6.8k elements, which forces me to use lx1=4, 5
![quarter-mesh](https://user-images.githubusercontent.com/31393012/59231183-69a81a80-8ba5-11e9-9869-8040098170e0.jpg)

**Comment by anshchaube** [comment]
The warning:
```
 L1/L2 DIV(V)-QTL       3.1925E+01   2.7392E+06
             WARNING: DIV(V)-QTL too large!
```

**Comment by anshchaube** [comment]
Made new mesh based on Kirk's suggestion. Has 4k elements. Compiles with lx1=6, lxd =9.
Files are here: https://github.com/arfc/sneks4me/tree/master/nekinput/quarter-channel
![newmesh](https://user-images.githubusercontent.com/31393012/59305343-b0f2e180-8c5f-11e9-82c7-e559262f2dfc.jpg)

New error with this mesh:
```
gs_setup: 7150 unique labels shared
   pairwise times (avg, min, max): 9.85066e-06 9.70364e-06 9.94205e-06
   crystal router                : 0.000168542 0.000166678 0.000169659
   all reduce                    : 9.46045e-05 9.42945e-05 9.49383e-05
   used all_to_all method: pairwise
   handle bytes (avg, min, max): 981433 972036 992268
   buffer bytes (avg, min, max): 38133.3 29280 48480
   setupds time 9.3272E-02 seconds   4  6      356340        4140
 Error in generalev, info=           7           6          -1

Matrix:   0 aa         6       6       6
 Error in generalev, info=           7           6          -1
  0 aa        Infinity     -Infinity   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00
  0 aa       -Infinity      Infinity  -4.51839E+01   6.59224E+00  -1.54366E+00   0.00000E+00
  0 aa     0.00000E+00  -4.51839E+01   7.71832E+01  -3.85916E+01   6.59224E+00   0.00000E+00
  0 aa     0.00000E+00   6.59224E+00  -3.85916E+01   7.71832E+01  -4.51839E+01   0.00000E+00
  0 aa     0.00000E+00  -1.54366E+00   6.59224E+00  -4.51839E+01   4.01353E+01   0.00000E+00
  0 aa     0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   1.00000E+00

Matrix:   0 bb         6       6       6
 Error in generalev, info=           7           6          -1
 Error in generalev, info=           7           6          -1
  0 bb     0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00
  0 bb     0.00000E+00   8.99735E-03   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00
  0 bb     0.00000E+00   0.00000E+00   4.49867E-02   0.00000E+00   0.00000E+00   0.00000E+00
  0 bb     0.00000E+00   0.00000E+00   0.00000E+00   4.49867E-02   0.00000E+00   0.00000E+00
  0 bb     0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   8.99735E-03   0.00000E+00
  0 bb     0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   1.00000E+00

Matrix:   0 Aeig       6       6       6
  0 Aeig      Infinity     -Infinity   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00
  0 Aeig     -Infinity      Infinity  -4.51839E+01   6.59224E+00  -1.54366E+00   0.00000E+00
  0 Aeig   0.00000E+00  -4.51839E+01   7.71832E+01  -3.85916E+01   6.59224E+00   0.00000E+00
  0 Aeig   0.00000E+00   6.59224E+00  -3.85916E+01   7.71832E+01  -4.51839E+01   0.00000E+00
  0 Aeig   0.00000E+00  -1.54366E+00   6.59224E+00  -4.51839E+01   4.01353E+01   0.00000E+00
  0 Aeig   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   0.00000E+00   1.00000E+00

Matrix:   0 Deig       1       6       6
  0 Deig   4.78698E+01   1.86339E+02   5.07658E+02   1.21717E+03   2.17067E+03   4.46408E+03
 Error in generalev, info=           7           6          -1
  
an error occured: dying ...
  
 Error in generalev, info=           7           6          -1
  
total elapsed time             :   8.27482E-01 sec
total solver time w/o IO       :   0.00000E+00 sec
time/timestep                  :   0.00000E+00 sec
avg throughput per timestep    :   0.00000E+00 gridpts/CPUs
total max memory usage         :   8.72444E-01 GB
```

**Comment by anshchaube** [comment]
https://lists.mcs.anl.gov/pipermail/nek5000-users/2014-May/002736.html

Probably an issue with BCs or subsets?

**Comment by anshchaube** [comment]
Kirk says the elements aren't lined up in the coarse and fine regions and that's why my Nek model isn't running. I'll try a few fixed in Trelis/Cubit, and if that doesn't work, I'll switch to gmsh. Kirk emailed his pipe example to me.

**Comment by anshchaube** [comment]
Kirk was right. Aligning element edges for the coarse and the fine region removed that error.

However, a coarse mesh with lx1=6 still does not remove the ` WARNING: DIV(V)-QTL too large! `. Divergence occurs at t = 0.5438. Will attempt to visualize results before that to identify the problem.

**Comment by anshchaube** [comment]
Added mesh with finer boundary layers and matching element nodes:
![finer-mesh](https://user-images.githubusercontent.com/31393012/59389098-1cf24a00-8d33-11e9-9b5f-d15164f473c3.jpg)

**Comment by anshchaube** [comment]
Now I'm getting the following error:
```
 Near X =  0.66095177      0.22432303       10.515142    , d:   0.0000000     -0.17672507E-02   1.3868889    
 WARNING1 Element mesh mismatch at:
 i,j,k,ie:    6    1    1        3953
 Near X =  0.66095177      0.22432303       10.515142    , d:   0.0000000     -0.17672507E-02   1.5129697    
 WARNING1 Element mesh mismatch at:
 i,j,k,ie:    6    4    1        3954
 Near X =  0.66095177      0.22432303       11.266731    , d:   0.0000000     -0.11356632E-02   1.5129697    
 WARNING1 Element mesh mismatch at:
 i,j,k,ie:    6    5    1        3954
 Near X =  0.66095177      0.22432303       10.762189    , d:   0.0000000     -0.15596476E-02   1.5129697    
 WARNING1 Element mesh mismatch at:
 i,j,k,ie:    6    6    1        3954
 Near X =  0.66095177      0.22432303       10.515142    , d:   0.0000000     -0.17672507E-02   1.5129697    
 Mesh consistency check failed.  EXITING in VRDSMSH.

```

**Comment by dshaver14** [comment]
The elements in this mesh still aren't conformal.  You can't have a vertex in the middle of a face on a neighboring element.


-------- Original message --------

**Comment by anshchaube** [comment]
To make mesh conformal in cubit - sweep across one volume/multiple surfaces (instead of multiple volumes - or use merge), turn off smoothing, allow redistribution of nodes (primary), allow "preserve" bias.

Mesh is conformal now and mesh errors are gone. But simulation still diverges. Cannot make finer without reducing lx1 from 6. Have reduced channel length by 75%. Will try smaller length with finer elements.

![new mesh](https://user-images.githubusercontent.com/31393012/59399098-6acd7900-8d58-11e9-8fb1-3a8cf732e875.jpg)

**Comment by anshchaube** [comment]
Trelis was creating elements with negative Jacobians on target surface
![jacobian](https://user-images.githubusercontent.com/31393012/59631971-b85a3500-910e-11e9-8c04-9430c94e4bc5.jpg)

**Comment by anshchaube** [comment]
Switched to gmsh. Was able to create a mesh that has the right number of elements and can compile with lx1=6 without overflow.

Ran Nek simulation. Residual seems to be decreasing. Hence, the model works.
