### ISSUE TITLE
Make coarser mesh

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#20]
Based on Prof. Fischer's feedback, we're trying to create a coarser mesh. This issue can be closed when a CHT mesh of no more than ~10k elements has been created, to make the simulations more tractable.

**Comment by anshchaube** [comment]
Old mesh:
![visit0000](https://user-images.githubusercontent.com/31393012/66581139-32db1480-eb45-11e9-855e-e144b8a474e2.png)
New mesh:
![visit0000](https://user-images.githubusercontent.com/31393012/66581184-47b7a800-eb45-11e9-97d9-4b8aab8b67d6.png)

**Comment by anshchaube** [comment]
@dshaver-ANL when merging the solid and fluid domain with prenek, do both need to have the same lx1 values? i.e. does prenek care about the conformity of the mesh without or with GLL points?

**Comment by dshaver14** [comment]
No.  Prenek knows absolutely nothing about lx1.


-------- Original message --------

**Comment by dshaver14** [comment]
This looks pretty good.  Can you add images showing the axial resolution?


-------- Original message --------

**Comment by anshchaube** [comment]
![visit0001](https://user-images.githubusercontent.com/31393012/66582048-c4975180-eb46-11e9-8ae8-75a39fa9e210.png)
Just the fluid.
```
 GLL grid spacing min/max: 6.09E-02 6.60E+00
scaled Jacobian min/max/avg: 5.80E-01/ 1.00E+00/8.31E-01
aspect ratio min/max/avg: 5.07E+00 3.54E+01 1.99E+01

```
(Haven't run a simulation yet, still dealing with some prenek merging problems. Will update if I get stuck.)

**Comment by anshchaube** [comment]
@dshaver-ANL after calling turboutflow, simulation diverges later (at 118/120s instead of 90/120s). But it still diverges. Files are on mcs cluster in `homes/achaube/chttest`.

**Comment by anshchaube** [comment]
Simulation is no longer diverging
![visit0001](https://user-images.githubusercontent.com/31393012/66778392-23cfcb80-ee91-11e9-87e3-c0325e76d559.png)
![visit0002](https://user-images.githubusercontent.com/31393012/66778395-25998f00-ee91-11e9-8cba-f81b6dbc76dd.png)

This is what worked (esp increasing `uin` to 1 from 0):
```
      parameter(lt=lx1*ly1*lz1*lelt)
      common /myoutflow/ d(lt),w1(lt)      
      ratio = 1.5
      uin = 1.0 ! was 0 before

      call turb_outflow(d,w1,ratio,uin)
```
I have a few questions @dshaver-ANL :
1. what just happened? what exactly did I fix here? prof. fischer mentioned something about uin being a scaling factor but I don't fully understand it.
2. there are some weird jumps/oscillations - v increases by a factor of 2 - not sure how to show it without a movie (files are in `/homes/achaube/chttest2` on the MCS cluster). Also, the vortices in the plenum are gone. The whole plenum looks very calm and static. ~~ Is this because of the aggressive filtering that Aleks mentioned?~~ simulations had no filter. Why is this happening?
3. I still see the simulation increasing the target CFL of 0.4 after t=118s or so. Does that mean these results are inaccurate? If the simulation diverges further down the line, say at t=240s, do we care about that at all?

**Comment by anshchaube** [comment]
@dshaver-ANL another odd observation - the simulation always exceeds the target CFL(0.4) ~~ towards the end, in this case ~~ around t = 120s. But if I give it the last field file (from 120s) and restart a new simulation from t=120s - 240s (`/homes/achaube/chttest3/`), the simulation returns to CFL<=targetCFL.

So I think it's exceeding the target CFL only ~~in the last few time steps of all my simulations~~ at about t=120s. No idea why.

**Comment by dshaver14** [comment]
I'm finally looking at your results from chttest2.  The transition is under resolved axially.  

![z-vel-transition](https://user-images.githubusercontent.com/20442860/66855669-50dfb500-ef49-11e9-9484-f65a98e5450b.png)

See how the minima and maxima are aligned with the axial grid spacing?  That's classic under-resolved behavior.  Keep in mind that the top of the graphite block is a solid wall, so it needs a boundary layer mesh just like the channel wall.  Inside the channel, you should geometrically decrease the thickness of the elements as it approaches the exit, then the first layer in the plenum should be the thinnest and from there you geometrically increase the thickness until you get back to something like you had.  If you are still concerned about element count, you might be able to get away with making the upstream mesh coarser still.

This is almost certainly what's causing all of your problems.  Messing around with div_outflow and filtering are all just red herrings... well filtering might be important for temperature, but we can revisit that issue once you get a flow field.

**Comment by anshchaube** [comment]
@dshaver-ANL I tried to make a mesh using gmsh with axial bias, so that the mesh is finer in the z direction near the plenum, but gmsh won't work. Prof. Fischer suggested that we use n2to3, using 0 zero layers and a text file with the z coordinates. I'm going to try and figure out how to do this now.

**Comment by dshaver14** [comment]
@anshchaube Using n2to3 will work fine, but rather than trying to hack something together that reads a text file, just do multiple extrusions, e.g. one extrusion with uniform density for the first part of the channel, a second with a geometric growth ratio less than 1 for the approach to the transition, a third with a ratio greater than 1 after the transition, and finally a 4th uniform distribution for the plenum.  You can then use prenek to merge all 4 of them.

**Comment by anshchaube** [comment]
![visit0000](https://user-images.githubusercontent.com/31393012/67129009-08333080-f1c3-11e9-9ad4-99107cd3ff72.png)
I feel like the mesh is adequately refined now. The results are in `PANDAVal/achaube/coarse-test`. It's just 12 files. Could you please take a look to confirm?
