### ISSUE TITLE
Use frozen velocity to speed up CHT

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#22]
Based on feedback by Aleks Obabko. High Pr = small thermal boundary layers = long computational time. "One way to speed it up is to use no temperature first to get velocity IC (say with faster OIFS/characteristic), then frozen-in-time velocity with tiny RHOCP for fast thermally relaxed IC and only then full conjugate heat"
https://www.mcs.anl.gov/~obabko/frozen.usr

This issue can be closed when the above suggestions have been implemented.

May not be critical since problem size has been reduced by 2 orders of magnitude.

**Comment by anshchaube** [comment]
Feedback from Dillon -  set `ifflow=.false.` in usrdat

**Comment by dshaver14** [comment]
You can only use a tiny rhoCp for the solid domain.  In the fluid domain the convective term is non-zero even for a frozen flow field so it must be set correctly.
