### ISSUE TITLE
Run a test case on blue waters

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#3]
This issue can be closed when a Nek job is successfully executed on Blue Waters, and the data from the run has been transferred and visualized.

**Comment by achubbz** [comment]
Same test case ran on desktop and yielded good results. But results from Blue Waters look unphysical:

![visit0000](https://user-images.githubusercontent.com/31393012/59936823-8f8bb580-9416-11e9-968d-f5f936bdce69.png)

**Comment by dshaver14** [comment]
This doesn’t look bad actually, just not fully developed.  Can you run it longer?  You would at least need to reach time = L/U.

-Dillon

**Comment by anshchaube** [comment]
I recently switched to Ubuntu 18, and I'm having trouble with visit. When I export the results, they look fine(which I realized after posting on Github). But when I'm viewing them in visit, I see big blocks in the middle of the channel where the velocity is zero. Currently trying to find an appropriate version of visit.

**Comment by anshchaube** [comment]
![visit0001](https://user-images.githubusercontent.com/31393012/59940344-12653e00-9420-11e9-8ec4-142597737ac3.png)
Data looks reasonable (although the boundary layer velocity seems to be zero). The problem was with VisIt. I think I can move on to #5 and start submitting bigger jobs that run for longer and close this issue @dshaver-ANL
