### ISSUE TITLE
Create simple mesh for conjugate heat transfer

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#6]
- [x] Create solid mesh using same coordinates from the fluid mesh to obtain a conformal mesh.
- [x] Convert fluid and solid `re2` files (w/ BCs ) to `rea` files using `gen_rea(2)` in `usrchk()`
- [x] Mesh solid and fluid `rea` files together using Prenek

**Comment by anshchaube** [comment]
Having trouble with step 3 : Nek's `gen_rea(2)` generates only the mesh data in its `newrea.out` file. The header and tail for the `rea` file that I need to add by hand are a bit of a mystery to me. I could take the top and the bottom of a 3d `rea` file from `Nek5000/examples` , but I am not sure how many parameters and logical flags I need to change from the original example. 

Do the `usr` and `par` files overwrite everything in the `rea` file, so it doesn't matter what's in it? If not, is there a smarter way to do this, instead of changing several parameters by hand @dshaver-ANL ?

**Comment by dshaver14** [comment]
You should blindly copy the head and tail to construct a complete rea file, then immediately convert it to an re2 file with reatore2.  The re2 file doesn’t contain any of the extra info from the head or tail, so it doesn’t matter what you put there.

**Comment by anshchaube** [comment]
Thanks! Kirk and I figured out that we need the head and the tail of an example rea file that is 3D and has thermal boundary conditions. We also removed the par file while running Nek in post-processing because Kirk was more comfortable with using rea files for this purpose. 

The rea files generated were finally accepted by prenek as valid input.

**Comment by achubbz** [comment]
However, when I used `reatore2` on prenek's' output and ran a Nek5000 simulation, this is the error I received:

```
  WARNING: DSSUM problem at:
 I,J,K,IE:    2    6    6        3385
  Near X =   1.0957728      0.50884470       12.836946    , d:   0.0000000      0.10000000E-02
  WARNING: DSSUM problem at:
 I,J,K,IE:    3    6    6        3385
  Near X =   1.0771351      0.51101954       12.836949    , d:   0.0000000      0.10000000E-02
  WARNING: DSSUM problem at:
 I,J,K,IE:    4    6    6        3385
  Near X =   1.0549087      0.51271589       12.836949    , d:   0.0000000      0.10000000E-02
  WARNING: DSSUM problem at:
 I,J,K,IE:    5    6    6        3385
  Near X =   1.0361565      0.51339471       12.836946    , d:   0.0000000      0.10000000E-02
  WARNING: DSSUM problem at:
 I,J,K,IE:    6    6    6        3385
  Near X =   1.0269555      0.51347783       12.836944    , d:   0.0000000      0.10000000E-02
 Mesh consistency check failed.  EXITING in VRDSMSH.
```

**Comment by anshchaube** [comment]
Further steps:
- [x] Setup par file
- [x] Setup BCs again

**Comment by achubbz** [comment]
@dshaver-ANL Hey Dillon, from http://nek5000.github.io/NekDoc/tutorials/conjht.html :
```In choosing viscosity=3.1623E-04 and conductivity=3.1623E-04, actually we are setting the Rayleigh Ra=10e7 and Prandtl Pr=1.```
What does this mean? What do I do if I want to enter the molten salt's Pr and Ra ?

**Comment by achubbz** [comment]
Also, my viscosity is set to -Re right now

**Comment by anshchaube** [comment]
I added test code to see if prenek was naming side sets correctly. I used this code in my `userbc` AND `useric`:
```     
     do iel=1,nelv
          do ifc=1,2*ndim
              id_face = bc(5,ifc,iel,1)
              bc(5,ifc,iel,2) = id_face
              if (id_face.eq.100) then       ! Inlet
                  temp = 1.0
              elseif (id_face.eq.10) then   ! Inlet graphite
                  temp = 1.0
              elseif (id_face.eq.1) then   ! Inlet graphite
                  temp = 0.5
              endif
          enddo
      enddo
```
![visit0000](https://user-images.githubusercontent.com/31393012/60367648-52926680-99b4-11e9-964d-54be98c52b9d.png)
As the attached image shows, some sidesets have the temp 0.5, meaning there are some sidesets labelled "1", even though I never created any sideset with this ID in gmsh. It seems prenek is creating random sideset IDs.

**Comment by achubbz** [comment]
The velocity boundary conditions using the same side set IDs seem to be working.

**Comment by anshchaube** [comment]
What worked - changing all solid/graphite boundary conditions to insulated, having only one user-specified temperature BC (at the inlet). I can now see the inlet temperature being propagated along the flow.

**Comment by anshchaube** [comment]
@dshaver-ANL I tried to set the volumetric heat source in the fluid region in my `usr` file as follows:
```
     subroutine userq(ix,iy,iz,eg) ! set source term

c      implicit none

      integer ix,iy,iz,eg

      include 'SIZE'
      include 'TOTAL'
      include 'NEKUSE'

      integer e
c     e = gllel(eg)

      qvol = 10.0
      if (eg.gt.nelgv) qvol = 0.0 ! glob el id > no. of el in glob v mesh

      return
      end
```
Does this seem correct?

**Comment by dshaver14** [comment]
looks right to me

**Comment by anshchaube** [comment]
Conjugate heat transfer works. I will post results that look physical once I have run a Nek simulation with the right non-dimensionalized thermal properties of the MSRE salt.

**Comment by anshchaube** [comment]
![visit0001](https://user-images.githubusercontent.com/31393012/60543252-723ecd00-9cdb-11e9-9666-ec2deac2a48f.png)
CHT is working. Inlet BC for temp is 1, which you can see propagating upwards. There's heat generation (qvol = 1.0) in the fluid which is also apparent. Mesh is functional.

Flow is not fully developed thermally. Future issues will focus on running a case with actual MSRE thermal properties until the flow is fully developed.
