### ISSUE TITLE
data spreadsheet

### ISSUE THREAD

**Issue by katyhuff** [arfc/sneks4me#8]
The data spreadsheet, in xlsx format, might be more useful in a csv format.

I certainly take some responsibility for this, as the first sheet was created by me.
Please consider using a plain text format, if you're going to version control this kind of data.
Additionally, I see that there is now another sheet (TH data) which contains no information regarding the source of any of the data in the spreadsheet.

This issue can be closed when :
- the data with no citations, in the TH data sheet, is documented with sources of each parameter,
- and the data spreadsheet is converted to a plain text format

**Comment by anshchaube** [comment]
I have been using this https://drive.google.com/file/d/1-lmth_iaFDs8i1UYXvGRsh2GbnaKwE32/view?usp=sharing
Is it fine if I periodically save this as a CSV in the repository? I have done that now.

**Comment by katyhuff** [comment]
perfect. A pro-tip: Include the link to the google doc in the csvs themselves.
