### ISSUE TITLE
Run Nek CHT on BW

### ISSUE THREAD

**Issue by anshchaube** [arfc/sneks4me#9]
Goals 
- [x]  See when the flow is fully-developed thermally
IMP: Set graphite temperature close to expected mean value in useric()

**Comment by anshchaube** [comment]
![visit0000](https://user-images.githubusercontent.com/31393012/61083203-c68b3080-a3f0-11e9-8fda-0b8924033cd5.png)
simulation works but temperature is too high - units are 1000 K (so highest temp is 5900K). Will double check source magnitude.

**Comment by anshchaube** [comment]
![visit0000](https://user-images.githubusercontent.com/31393012/61088412-eecd5c00-a3fd-11e9-8aca-db474416d2a4.png)
Temperatures are the right order of magnitude but:
- graphite temperature is too low (908 vs 952-977 K)
- salt temperature at outlet is kinda low (927 vs 935-955 K)

Fixes : 
- [x]  Change IC for graphite (possibly salt as well?)
- [x]  Run simulation for longer (current runtime - 120 s)

**Comment by anshchaube** [comment]
![visit0000](https://user-images.githubusercontent.com/31393012/61227720-752dba80-a6ea-11e9-8c5c-f86fa88a5ebd.png)
After 1200 s and an IC of 955 K, the graphite in the middle of the channel cools to a value somewhat close to the value mentioned in ORNL TM 728.
![visit0001](https://user-images.githubusercontent.com/31393012/61227721-765ee780-a6ea-11e9-942c-2a2307aca0f3.png)
However, near the top, the graphite is somewhat hotter than expected (962 K), in a localized are to the right.

It seems the simulation hasn't reached steady state after 1200 s. Will try running for longer.

**Comment by anshchaube** [comment]
![visit0002](https://user-images.githubusercontent.com/31393012/61238935-54be2a00-a703-11e9-9f5d-f31afce1eab8.png)

**Comment by anshchaube** [comment]
Dillon - "Try disabling Nek's solve for the velocity field once it has converged"

**Comment by anshchaube** [comment]
Fix solid mesh - top - BC

**Comment by anshchaube** [comment]
<img width="872" alt="Screen Shot 2019-07-26 at 4 36 21 PM" src="https://user-images.githubusercontent.com/31393012/61982844-9f715900-afc3-11e9-801c-33dc28bc16ef.png">
Normalization = Tbar = (T - Tinlet) /(dT)
Tinlet = 908 K
dT = 0.2277 K.

**Comment by anshchaube** [comment]
@katyhuff mentioned this result doesn't look physical - the top of the graphite in the image above is as hot as the middle of the channel. After having thought about it - I think it is physical. The graphite starts out as cold and gets hotter and hotter - you can see the heat traveling from the centre of the channel to the top right (blue) corner. The graphite is completely insulated - so it continues to heat up. If I had let this simulation run longer, the graphite would be even hotter than the centre of the channel.

Summary - the insulation boundary condition explains this result. The temperature values being the same in the graphite and the channel at t=1000s is pure coincidence.

@katyhuff if you have questions about how Nek calculates friction factors, I think @dshaver-ANL would know best. I don't have an answer to that question.

**Comment by dshaver14** [comment]
It is physical.  I would definitely expect the highest temperature in the fuel to be at the outlet and as you said, the graphite is insulated, so the only mechanism for it to cool down is to transfer heat to the fuel, which it cannot do unless it is hotter.  To get a better solution, we will need to include the plenum on top.  We could also change the boundary condition from insulated to convective, but then we would need to estimate the fuel temperature and heat transfer coefficient. 

@katyhuff Nek5000 doesn't calculate friction factors.  The pressure field is part of the solution to the Navier-Stokes equations.  To get a friction factor, we would need to extract pressure drop and calculate it in post.
